[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[inet_http_server]
port = 0.0.0.0:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl = http://127.0.0.1:9001



[program:xvfb]
command=Xvfb :99 -screen 0 %(ENV_SCREEN_WIDTH)sx%(ENV_SCREEN_HEIGHT)sx%(ENV_SCREEN_DEPTH)s -ac -noreset
autorestart=true
priority=10

[program:x11vnc]
command=x11vnc -display :99 -forever -shared -nopw -rfbport 5900 -listen 127.0.0.1 -wait 50
autorestart=true
priority=20

[program:websockify]
command=websockify --web /usr/share/novnc 6080 127.0.0.1:5900
autorestart=true
priority=30

[program:cdp-relay]
command=socat TCP-LISTEN:9222,fork,reuseaddr TCP:127.0.0.1:9223
autorestart=true
priority=35

[program:chromium]
command=/app/launch_chromium.sh
user=chromeuser
environment=HOME="/home/chromeuser",USER="chromeuser",DISPLAY=":99"
autorestart=true
priority=40
