# Generated by Django 5.2.4 on 2026-09-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Marked as favorite contact'),
        ),
    ]
