# Generated by Django 5.2.4 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserProxyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(default='Decodo', max_length=50)),
                ('protocol', models.CharField(default='http', max_length=20)),
                ('host', models.CharField(blank=True, default='gate.decodo.com', max_length=255)),
                ('port', models.IntegerField(default=7000)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(default='US', max_length=10)),
                ('session_type', models.CharField(default='sticky', max_length=20)),
                ('session_duration', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Browser Proxy Configuration',
                'verbose_name_plural': 'Browser Proxy Configurations',
            },
        ),
    ]
