# Generated by Django 5.2.4 on 2026-09-06 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(max_length=100)),
                ('auth_token', models.CharField(help_text='Twilio Auth Token - stored encrypted in production', max_length=200)),
                ('phone_number', models.CharField(help_text='Twilio phone number in E.164 format e.g. +15551234567', max_length=20)),
                ('cnam_name', models.CharField(blank=True, help_text='Caller ID Name (CNAM) - max 15 characters', max_length=15)),
                ('twiml_app_sid', models.CharField(blank=True, help_text='TwiML App SID for browser-based calling', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twilio Configuration',
                'verbose_name_plural': 'Twilio Configurations',
            },
        ),
    ]
