# Generated by Django 5.2.4 on 2026-09-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioconfig',
            name='api_key_secret',
            field=models.CharField(blank=True, default='', help_text='Twilio API Key Secret', max_length=200),
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='api_key_sid',
            field=models.CharField(blank=True, default='', help_text='Twilio API Key SID starting with SK...', max_length=100),
        ),
    ]
