# Generated by Django 5.2.4 on 2026-09-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_config', '0002_twilioconfig_api_key_secret_twilioconfig_api_key_sid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twilioconfig',
            options={'verbose_name': 'Telephony Configuration', 'verbose_name_plural': 'Telephony Configurations'},
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='provider_type',
            field=models.CharField(choices=[('twilio', 'Twilio Native SDK'), ('asterisk', 'Asterisk / Custom SIP Provider')], default='twilio', help_text='Active telephony provider engine', max_length=20),
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='sip_domain',
            field=models.CharField(blank=True, default='', help_text='SIP Domain / Realm e.g. sip.voipgate.com or asterisk.local', max_length=200),
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='sip_outbound_proxy',
            field=models.CharField(blank=True, default='', help_text='Optional SIP Outbound Proxy', max_length=200),
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='sip_password',
            field=models.CharField(blank=True, default='', help_text='SIP Password / Secret', max_length=200),
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='sip_username',
            field=models.CharField(blank=True, default='', help_text='SIP Extension or Username e.g. 1001 or agent1', max_length=100),
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='sip_ws_url',
            field=models.CharField(blank=True, default='', help_text='WebSocket URL e.g. wss://asterisk.example.com:8089/ws', max_length=255),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='account_sid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='auth_token',
            field=models.CharField(blank=True, default='', help_text='Twilio Auth Token - stored encrypted in production', max_length=200),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='cnam_name',
            field=models.CharField(blank=True, default='', help_text='Caller ID Name (CNAM) - max 15 characters', max_length=15),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Twilio or SIP outbound phone number in E.164 format e.g. +15551234567', max_length=20),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='twiml_app_sid',
            field=models.CharField(blank=True, default='', help_text='TwiML App SID for browser-based calling', max_length=100),
        ),
    ]
