# Generated by Django 5.2.4 on 2026-09-06 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, help_text='Call duration in seconds')),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('busy', 'Busy'), ('voicemail', 'Voicemail'), ('wrong_number', 'Wrong Number'), ('do_not_call', 'Do Not Call'), ('no_answer', 'No Answer')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('call_sid', models.CharField(blank=True, help_text='Twilio Call SID for reference', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='contacts.contact')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
